### ISSUE TITLE
Support Mapping Property Names to Faker Methods

### ISSUE THREAD

**Issue by aidan-casey** [Anteris-Dev/data-transfer-object-factory#10]
Continued from #5 where @morrislaptop suggested the following.

> I had another idea as well - mapping DTO property names to faker instances e.g.
> ```php
> class Employee extends DataTransferObject
> {
>     public string $address;
> }
> ```
> Then instead of just calling $faker->word, we would call $faker->address, what do you think?
> 
> Example: https://github.com/mpociot/laravel-test-factory-helper

I think this is an excellent idea and a good opportunity to increase the usefulness of this package.

**Comment by morrislaptop** [comment]
Should be quite easy with https://github.com/laravel-shift/faker-registry 👍

**Comment by aidan-casey** [comment]
Yup. One thing I'm checking right now is if there is any possibility of collecting those methods at runtime. The only reason being that then it could support custom faker providers as well. Not sure if it's worth it or not, but a thought.

**Comment by aidan-casey** [comment]
Heh, faker also has a `format()` method which would be even easier. Handles that guessing built-in.

**Comment by morrislaptop** [comment]
True, might be worth checking the manually mapped field names from that
repo as well :)

**Comment by aidan-casey** [comment]
I did take a look at Jason's work and it looks great in a different context. That package is primarily geared toward generating factory files. While we could certainly make it work, it seemed easiest to create a new package that is aligned a little more toward what we are after. We did borrow some of that dictionary array, but it is revised from string template form to a multi-dimensional array so we can programmatically handle function parameters without any hacks.

We also wanted to add in a little more guess work before manually mapping. We fallback on manual maps, but start with guessing.

That package now exists [here](https://github.com/Anteris-Dev/faker-map). 🙂

**Comment by aidan-casey** [comment]
Made this work with some success this evening. Got the following output:

```php
Tests\TestData\TestPersonDTO Object
(
    [firstName] => Mittie
    [lastName] => Pfannerstill
    [email] => conroy.clifton@schneider.net
    [company] => Moore PLC
    [homeAddress] => 50298 Giuseppe Grove
North Kristofer, MO 15872
    [city] => Gaetanobury
    [state] => New Jersey
    [zip] => 45783
    [phoneNumber] => (705) 942-3927 x6600
    [ignoreMissing:protected] => 
    [exceptKeys:protected] => Array
        (
        )

    [onlyKeys:protected] => Array
        (
        )

)
```

From the following input (using a new API I am testing):

```php
DataTransferObjectFactory::make(TestPersonDTO::class)->create();
```

**Comment by morrislaptop** [comment]
Wow this is way more advanced than what I was expecting, nice work!

**Comment by aidan-casey** [comment]
Haha! Thanks. Go big or go home right? 😉
