### ISSUE TITLE
Should auto create child DTO objects as well

### ISSUE THREAD

**Issue by morrislaptop** [Anteris-Dev/data-transfer-object-factory#5]
```php
class Address extends DataTransferObject
{
    public string $line1;
}

class CreateOrder extends DataTransferObject
{
    public Address $address;
}

DataTransferObjectFactory::make(CreateOrderDTO::class);
```

I'd expect the the factory to detect that $address is a DTO of type Address and auto make that as well? What do you think?

**Comment by aidan-casey** [comment]
Hey @morrislaptop! You are correct, the factory should be returning a DTO in that scenario. It would appear that was an oversight on my part.

In the the initial stages of this package we did not follow Spatie's approach to type casting and allowed collections to be generated based on the property type in addition to doc block support. It looks like when we removed that approach and aligned this package with how Spatie does things, we inadvertently removed support for generating DTOs based on their type as well.

I will add this to the to do list, but in the meantime you can get around this in one of two ways:

## Doc block

```php
class Address extends DataTransferObject
{
    public string $line1;
}

class CreateOrder extends DataTransferObject
{
    /** @var Address */
    public Address $address;
}

DataTransferObjectFactory::make(CreateOrder::class);
```

## Custom Factory
```php
class Factory extends DataTransferObjectFactory
{
    public static function makeAddress(): Address
    {
        return static::make( Address::class );
    }
}
```

**Comment by aidan-casey** [comment]
Fixed! Just remember to use the FQDN in your DTO. 👍

**Comment by morrislaptop** [comment]
Nice! I had another idea as well - mapping DTO property names to faker instances e.g. 

class Employee extends DataTransferObject
{
    public string $address;
}

Then instead of just calling $faker->word, we would call $faker->address, what do you think?

**Comment by aidan-casey** [comment]
Love this idea! Let me create a separate issue for that so we can track it there. May be a good time to implement this as we consider some changes for PHP 8 as well.
